macro(list_directories RESULT DIRECTORY)
	file(GLOB CHILDREN RELATIVE ${DIRECTORY} ${DIRECTORY}/*)
	set(DIRECTORIES "")
	foreach(CHILD ${CHILDREN})
		if(IS_DIRECTORY ${DIRECTORY}/${CHILD})
			list(APPEND DIRECTORIES ${CHILD})
		endif()
	endforeach()
	set(${RESULT} ${DIRECTORIES})
endmacro()